added Custom RankCard System
SlimeCloud/java-SlimeBot pull request #109
Opened 2023-08-05 12:44 UTC by cyklon73

## Checklist

 - [X] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#-contributing) and [Style Guides](https://github.com/SlimeCloud/java-SlimeBot#-style-guide)
 - [ ] Test the Code
 - [ ] This PR is ready to review and merge

## Description
Describe what you have changed

## Related Issue
N/A

## Other Information
Custom RankCard System implemented.
Commands still missing

2023-08-28 16:08 UTC, MatitoDA requested changes
[siehe dc](https://discord.com/channels/1077255218728796192/1099133413736317100/1145745715088326806)

2023-09-07 13:44 UTC, MineKing9534 requested changes

2023-09-07 13:44 UTC, MineKing9534 commented on README.md
> +Um mit der Datenbank zu interagieren wird eine sogenannte `DataClass` benötigt. Diese Klasse enthält alle daten die gespeichert werden sollen als Variabeln (es werden nur primitive typen, Strings und
daten -> Daten,
typen -> Typen (Ich seh grad, dass war vorher auch schon falsch, aber fix das bitte trotzdem xD)

2023-09-07 13:44 UTC, MineKing9534 commented on src/main/java/com/slimebot/level/RankCard.java
> +import static com.slimebot.level.profile.Style.ROUND;
Please don't use a static import here, just use Style.ROUND when the enum constant is used

2023-09-10 20:19 UTC, MineKing9534 requested changes
Please do a IntelliJ reformat code

2023-09-10 20:25 UTC, MineKing9534 approved these changes

2023-09-11 19:18 UTC, MatitoDA requested changes
If you Change the Background, there a some bugs:

- if you set an Image as Background and then want to set a Color as background, the Image does not disappear.
- if you set an invalid image link/color, there is no feedback for the user

2023-09-11 19:42 UTC, MineKing9534 requested changes

2023-09-11 19:42 UTC, MineKing9534 commented on src/main/java/com/slimebot/commands/level/card/CardCommand.java
> +@ApplicationCommand(name = "card", description = "passe deine rank card an", feature = "level")
Passe deine Rankcard an

2023-09-11 19:42 UTC, MineKing9534 commented on src/main/java/com/slimebot/commands/level/card/CardCommand.java
> +	@ApplicationCommand(name = "edit", description = "bearbeite deine rankcard")
Bearbeite deine Rankcard

2023-09-11 19:42 UTC, MineKing9534 commented on src/main/java/com/slimebot/commands/level/card/CardCommand.java
> +	@ApplicationCommand(name = "info", description = "zeigt deine aktuellen rankcard optionen an")
Zeigt deine aktuellen Rankcard Optionen an

2023-09-11 20:55 UTC, MatitoDA approved these changes

2023-09-11 20:59 UTC, MineKing9534 requested changes
Please do a reformat with tabs enabled, you replace all indentations with spaces

2023-09-11 21:14 UTC, MineKing9534 approved these changes

2023-09-11 21:16 UTC, merged