Spotify Token Fix
SlimeCloud/java-SlimeBot pull request #113
Opened 2023-08-14 15:15 UTC by Byteingpython

## Checklist

 - [x] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#-contributing) and [Style Guides](https://github.com/SlimeCloud/java-SlimeBot#-style-guide)
 - [x] Test the Code
 - [x] This PR is ready to review and merge

## Description
The spotify Api instance is now created new every time the episodes are fetched to avoid token expiration

## Related Issue
#112 

## Other Information

2023-08-14 19:15 UTC, MineKing9534 requested changes
You should rather only get a new access token without creating an entire new instance of the spotify api class. Simple put the setup code back into the constructor and only call the setAccessToken part multiple times. Also, instead of getting a new token for every request you should rather save the expire of the token and only request a new one if the old one is expired. To do so, you can store a long that holds the expiry timestamp. Every time you get a new token, you set this long to `System.currentTimeMillis() + token.getExpiresIn() * 1000` and only update the token `if(System.currentTimeMillis() > tokenExpiry`.

2023-08-16 21:04 UTC, MineKing9534 requested changes

2023-08-16 21:04 UTC, MineKing9534 commented on src/main/java/com/slimebot/alerts/spotify/SpotifyListener.java
> +	private void fetchToken(SpotifyApi api){
Why do you have the SpotifyApi as parameter? It is available as field in the class

2023-08-16 21:04 UTC, MineKing9534 commented on src/main/java/com/slimebot/alerts/spotify/SpotifyListener.java
> +	private long tokenExpiry=0;
Formatting should be `tokenExpiry = 0`.

2023-08-16 21:04 UTC, MineKing9534 commented on src/main/java/com/slimebot/alerts/spotify/SpotifyListener.java
> +		if(System.currentTimeMillis()>tokenExpiry){
Missing spaces: `if (.. > ..)`
Don't use `{}` for single line blocks

2023-08-16 21:04 UTC, MineKing9534 commented on src/main/java/com/slimebot/alerts/spotify/SpotifyListener.java
> +	public SpotifyListener(){
Missing space between `()` and `{`

2023-08-17 13:40 UTC, MineKing9534 approved these changes

2023-08-25 17:36 UTC, MatitoDA approved these changes

2023-08-25 17:38 UTC, merged