Statistic channel
SlimeCloud/java-SlimeBot pull request #161
Opened 2024-01-01 16:48 UTC by cyklon73

## Checklist

 - [X] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#-contributing) and [Style Guides](https://github.com/SlimeCloud/java-SlimeBot#-style-guide)
 - [ ] Test the Code
 - [ ] This PR is ready to review and merge

## Description
Replace MEE6: Statistic channels

## Related Issue
[issue](https://github.com/SlimeCloud/java-SlimeBot/issues/97)

## Other Information
N/A

2024-01-02 12:37 UTC, MineKing9534 approved these changes

2024-01-02 12:39 UTC, MineKing9534 requested changes

2024-01-02 12:39 UTC, MineKing9534 commented on src/main/java/de/slimecloud/slimeball/features/statistic/MemberCount.java
> +	private final Function<StatisticConfig, Long> channel;
Why are you storing these methods? Just call them without the method reference

2024-01-02 20:00 UTC, MineKing9534 approved these changes

2024-01-07 07:50 UTC, MineKing9534 requested changes

2024-01-07 07:50 UTC, MineKing9534 commented on src/main/java/de/slimecloud/slimeball/features/statistic/StatisticConfig.java
> +
Update channels in this method

2024-01-07 11:48 UTC, MineKing9534 approved these changes

2024-01-08 18:46 UTC, MatitoDev requested changes
RoleMemberCount Formatierung don't work/don't update.
I tried to update the formatting by changing the member count, but the formatting is still the old one

![image](https://github.com/SlimeCloud/java-SlimeBot/assets/77804268/c53e853a-d315-45f9-b7ea-84a44fadc9b7)

2024-01-10 15:25 UTC, MatitoDev approved these changes

2024-01-10 15:25 UTC, merged