Brithday
SlimeCloud/java-SlimeBot pull request #166
Opened 2024-01-02 12:41 UTC by cyklon73

## Checklist

 - [x] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#-contributing) and [Style Guides](https://github.com/SlimeCloud/java-SlimeBot#-style-guide)
 - [ ] Test the Code
 - [ ] This PR is ready to review and merge
 - [x] /birthday {target}   no target -> author   -> shows the birthday of the target user
- [ ] /next-birthdays shows the next 10 birthdays
- [ ] /remember-birthday {day} {month} [optional]{year} Add the specified birthday to the system (if the user is already in the system, the existing entry will be overwritten)
- [ ] /forget-brithday rremove the author's birthday from the system

## Description
Replace MEE6: replace Birhtday System from MEE6

## Related Issue
[issue](https://github.com/SlimeCloud/java-SlimeBot/issues/100)

## Other Information
N/A

2024-01-02 12:55 UTC, MineKing9534 commented
- use subcommands (/birthday list, /birthday remember, etc.)
- use instant instead of LocalDateTime (You dont need to write a mapper for that, instant is supportet by default)

2024-01-02 13:10 UTC, cyklon73 commented
> * use subcommands (/birthday list, /birthday remember, etc.)
> * use DiscordUtils list frature for listing
> * use instant instead of LocalDateTime (You dont need to write a mapper for that, instant is supportet by default)

- will be done
- what exactly do you mean by list feature, and which listing?
- I will stick with LocalDateTime because it has some features that Instant doesn't have but that I need

2024-01-02 17:03 UTC, MineKing9534 approved these changes

2024-01-02 20:26 UTC, MatitoDev requested changes
Can't find code for Birthday Announcement and Role (if this is because of the config shit, i wait with merging until #165 is done)
=> can't test this anyway

When Year is given:
- display age in list, info and Announcement
- give alert to user (?) and team if the age is under 16

2024-01-07 12:07 UTC, MineKing9534 commented on src/main/java/de/slimecloud/slimeball/features/birthday/BirthdayConfig.java
> +	public long announceChat;
I think we can sue the greeetingsChannel config value instead of a new one

2024-01-08 18:13 UTC, MatitoDev approved these changes
If the Alert-System is tested from your side, it's approved.

have a look at minekings review.

2024-01-10 15:01 UTC, MatitoDev approved these changes

2024-01-16 17:09 UTC, merged