Fix quote cooldown
SlimeCloud/java-SlimeBot pull request #217
Opened 2024-03-28 19:40 UTC by MineKing9534

## Checklist

 - [x] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#-contributing) and [Style Guides](https://github.com/SlimeCloud/java-SlimeBot#-style-guide)
 - [x] Test the Code
 - [x] This PR is ready to review and merge

2024-03-30 10:15 UTC, cyklon73 approved these changes

2024-04-04 15:14 UTC, MatitoDev requested changes
DCUtils or your maven site has an issue

[GitHub Action](https://github.com/SlimeCloud/java-SlimeBot/actions/runs/8472804016/job/23448213559?pr=217)
```
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find de.mineking:DiscordUtils:c45bd72.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/de/mineking/DiscordUtils/c45bd72/DiscordUtils-c45bd72.pom
       - https://maven.mineking.dev/releases/de/mineking/DiscordUtils/c45bd72/DiscordUtils-c45bd72.pom
       - https://maven.mineking.dev/snapshots/de/mineking/DiscordUtils/c45bd72/DiscordUtils-c45bd72.pom
       - https://jitpack.io/de/mineking/DiscordUtils/c45bd72/DiscordUtils-c45bd72.pom
     Required by:
         project :
Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

2024-04-04 16:21 UTC, MineKing9534 commented
fixed

2024-04-04 16:25 UTC, MatitoDev approved these changes

2024-04-04 16:25 UTC, merged