Create Spotify Listener
SlimeCloud/java-SlimeBot pull request #28
Opened 2023-06-26 15:33 UTC by Byteingpython

## Checklist

 - [ ✅] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#contributing)
 - [✅ ] Tested the Code
 - [ ✅] This PR is ready to review and merge

## Description:
Ich habe ein System hinzugefügt, das automatisch ein mal am Tag überprüft, ob bei einem Künstler
auf spotify ein neues album erschienen ist und dann eine Nachricht schickt

## Related Issue
https://github.com/SlimeCloud/java-SlimeBot/issues/6

## Other Information
Da es bei mir nur so funktioniert hat habe ich die implementation von Simpleyaml auf das, was jitpack.io angezeigt hat geändert habe. Sonst habe ich diesen Error bekommen:Ich hab nen problem. Wenn ich den SlimeBall bot klone und versuche ihn auszuführen bekomme ich den Error:  https://pastebin.com/XFqEr3eC

2023-06-26 17:56 UTC, MatitoDA commented
Überprüft das auch Podcasts? 
wäre praktisch für den Slimecast.

2023-06-26 18:28 UTC, MatitoDA requested changes
Füge bitte noch was ein, dass er direkt beim Start vom bot einmal auf Releases überprüft, das macht das Testen einfacher :)

2023-06-26 19:05 UTC, Byteingpython commented
> Überprüft das auch Podcasts? 
> wäre praktisch für den Slimecast.

Nein. Podcasts sind anders geregelt. Das würde ich auch anders coden

2023-06-27 18:40 UTC, Byteingpython commented
Ich habe jetzt zu einem System, das auf den Alben IDs basiert gewechselt. So ist es jetzt auch möglich, das direkt beim Start überprüft wird

2023-06-27 19:44 UTC, MatitoDA approved these changes
Beim Erstellen der Config werden noch alle Alben des Artist gespamt, ist aber nicht schlimm. Da kann man ja auf nem test dc sich die Config mit den ganzen Alben-IDs erstellen lassen und die Config dann aufm Main bot auch nutzen.

2023-06-27 19:46 UTC, merged