Added the fdmds command
SlimeCloud/java-SlimeBot pull request #31
Opened 2023-06-27 00:58 UTC by Deliasama

## Checklist

 - [ yes] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#contributing)
 - [yes ] Tested the Code
 - [yes ] This PR is ready to review and merge

## Description:
I added the "Frag doch mal den Schleim" command, that was wished in #10

## Related Issue
/

## Other Information
The "design" should be revised (the feedback messages and the modal).

2023-06-27 01:00 UTC, Deliasama commented
Ignoriert die commit messages ^^' Ich hab alles im ersten commit gemacht, die anderen 2 commits haben nur Formatierungsfehler meinerseits behoben.

2023-06-27 15:56 UTC, Deliasama commented
> So ist das glaube ich ehrlich gesagt gar nicht so hilfreich. Richtig cool wäre es, wenn du es noch irgendwie schaffen würdest, dass Mods mit /fdmds die Frage gleich in den chat stellen können, oder was richtig cool wäre (und auch sehr praktisch), dass der Staff nur noch die fragen approven müsste und dann einmal am Tag automatisch eine reingeschickt wird. Das wäre zumindest meine Idee

Das könnte ich natührlich machen aber so müssten die mods das ja nur copy pasten... und die müssten das sowieso noch ändern etc weil ich nicht denke das die user das gut hinbekommen

2023-06-27 16:02 UTC, Byteingpython commented
Ich glaube allerdings, das da lieber noch etwas länger dran rumgetüftelt werden sollte. Dann kommt vlt. ja was echt neues Raus. So ist es auf jeden Fall für die Mods glaube ich nicht einfacher, als einfach aus https://discord.com/channels/1077255218728796192/1115648785587109958 zu Copy pasten

2023-06-27 17:55 UTC, Deliasama commented
Guckt es euch jetzt mal an ist noch nicht perfekt aber es geht hoffentlich in die richtige richtung (das mit den emoji konnte ich noch nicht testen)

2023-06-27 21:24 UTC, MatitoDA requested changes
Hab mal drüber geschaut und einige Kleinigkeiten geändert.

Das mit den Emojis funktioniert bei den Reactions so weit. In der Nachricht werden die Emojis jedoch noch nicht richtig angezeigt.
Das hab ich jetzt auf die schnelle aber grade nicht gefixt bekommen.

2023-06-27 21:37 UTC, Deliasama commented
> 

wie werden die emoji denn in der nachricht angezeigt?

2023-06-27 21:49 UTC, MatitoDA commented
Nur der name wird angezeigt

![IMG_20230627_234828.jpg](https://github.com/SlimeCloud/java-SlimeBot/assets/77804268/cb746f94-f657-43ef-8d88-6476139cface)

2023-06-27 21:50 UTC, Deliasama commented
> Nur der name wird angezeigt
> 
> ![IMG_20230627_234828.jpg](https://user-images.githubusercontent.com/77804268/249293593-cb746f94-f657-43ef-8d88-6476139cface.jpg)

da fehlen aber auch reaktions, hast du vorher edit genutzt?

2023-06-27 21:58 UTC, MatitoDA commented
Hab nur die ersten drei als emoji aufm test dc, deswegen fehlen da welche xd
Im embed wird auch nur der name Angezeigt

2023-06-27 22:01 UTC, Deliasama commented
> Hab nur die ersten drei als emoji aufm test dc, deswegen fehlen da welche xd Im embed wird auch nur der name Angezeigt

huh wenn das ein anderer Server ist mit eigenen emojis, hast du dann die namen im Enum auf deine emojis geändert, weil die id ist ja anders

2023-06-27 22:07 UTC, MatitoDA commented
> > Hab nur die ersten drei als emoji aufm test dc, deswegen fehlen da welche xd Im embed wird auch nur der name Angezeigt
> 
> huh wenn das ein anderer Server ist mit eigenen emojis, hast du dann die namen im Enum auf deine emojis geändert, weil die id ist ja anders

ID und name hab ich angepasst, ja klar. Hat ja bei den Reaktionen auch funktioniert

2023-06-27 22:18 UTC, Deliasama commented
> 

ok ob dus glaubst oder nicht bei mir klappt es
![image](https://github.com/SlimeCloud/java-SlimeBot/assets/115506148/50804f67-df09-455f-b270-f003628f0bea)

2023-06-28 15:29 UTC, MatitoDA approved these changes

2023-06-28 15:39 UTC, Deliasama commented
Willst du das embed nicht einfach löschen wenn es versendet wurde?

2023-06-28 15:40 UTC, MatitoDA commented
> Willst du das embed nicht einfach löschen wenn es versendet wurde?

ne so kann man besser nachvoll ziehen wer eine Frage gestellt hat, denke ich

2023-06-28 16:06 UTC, merged