Automatisches updaten der Staff Message
SlimeCloud/java-SlimeBot pull request #37
Opened 2023-06-30 14:21 UTC by Byteingpython

## Checklist

 - [ ✅ ] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#contributing)
 - [ ✅ ] Tested the Code
 - [ ✅ ] This PR is ready to review and merge

## Description:
Es gibt jetzt pro Guild eine neue Config, mit der man automatisches updaten der
Teamvorstellungs Message konfigurieren kann.

## Related Issue
[issue](https://github.com/SlimeCloud/java-SlimeBot/issues/26)

## Other Information
Nix

2023-07-09 14:29 UTC, MatitoDA requested changes
Wir haben 2 Sektionen in der Teamnachricht:
Leute die im Main Team sind und Leute die z. B. noch in der Testphase sind oder sich um Events kümmern. Könntest du das noch sichtbar bitte trennen?

2023-07-09 14:29 UTC, MatitoDA commented on src/main/java/com/slimebot/message/StaffMessage.java
> +            config.setComment("message", "Is shown before the roles");
ich fände es cool noch die Möglichkeit zu haben auch nach den Rollen noch etwas zu schreiben also praktisch ein e `pre-msg`, `mid-msg` (für z.B. zwischen den Sektionen) und `sub-msg`.

2023-07-09 15:17 UTC, Byteingpython commented on src/main/java/com/slimebot/message/StaffMessage.java
> +            config.setComment("message", "Is shown before the roles");
Jetzt kannst du einfach zwischen den ganzen rollen irgendeinen nicht als Long parsebaren key mit der message als value, die du an dem punkt haben willst, einfügen

2023-07-11 15:23 UTC, MatitoDA approved these changes

2023-07-11 15:25 UTC, merged