FDMDS improvements
SlimeCloud/java-SlimeBot pull request #40
Opened 2023-07-01 14:25 UTC by Byteingpython

## Checklist

 - [ ✅ ] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#contributing)
 - [ ✅ ] Tested the Code
 - [ ✅ ] This PR is ready to review and merge

## Description:
* "Heute würde ich gerne von euch wissen, " is now added before the question in the embed
* Set Answer example to Antworten mit ; trennen z.B. Erdbeere; Cookie; Schokolade
* Added config for a role to mention

## Related Issue
This PR is related to Issue [39](https://github.com/SlimeCloud/java-SlimeBot/issues/39)?

## Other Information

2023-07-02 19:27 UTC, MatitoDA requested changes
Bitte User-Feedback bei `getRoleMentionFromConfig()` hinzufügen, sodass nicht nur „Interaktion fehlgeschlagen“ da steht

2023-07-02 20:01 UTC, Byteingpython commented
> Bitte User-Feedback bei `getRoleMentionFromConfig()` hinzufügen, sodass nicht nur „Interaktion fehlgeschlagen“ da steht 

Im log oder direkt zum user

2023-07-02 21:18 UTC, MatitoDA commented
> > Bitte User-Feedback bei `getRoleMentionFromConfig()` hinzufügen, sodass nicht nur „Interaktion fehlgeschlagen“ da steht 
> 
> Im log oder direkt zum user?

Direkt dem user.

Und es wurde sich noch gewünscht das die Nachricht statt editiert komplett gelöscht wird, wäre lieb wenn du dass auch noch direkt machen könnest

2023-07-03 14:37 UTC, MatitoDA approved these changes

2023-07-03 14:38 UTC, merged