General code cleanup and improvement
SlimeCloud/java-SlimeBot pull request #42
Opened 2023-07-07 06:03 UTC by MineKing9534

## Checklist

 - [x] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#contributing)
 - [ ] Tested the Code
 - [ ] This PR is ready to review and merge

## Description:
The Main class was quite unorganized. I tried to clean it up a little by extracting the command registration into its own method. I also fixed the command registration that deleted all commands after creating them before. The input that asks for a token name to use at startup was replaced by the first command line parameter.
The command handling still doesn't work because the listeners in the command classes use #getName instead of #getFullCommandName.
Currently there is no uniform code style. I will format all code with the style that is most used. If @MatitoDA prefers a different one, you can comment it below so I will change it to the style you prefer. 

- [x] Improve startup
- [x] Cleanup command registration
- [ ] Fix command handing (waiting for response whether to use a system similar to the current one or a CommandManager)
- [ ] Format all code according to a uniform pattern

## Related Issue
N/A

## Other Information
N/A

2023-07-07 19:24 UTC, MatitoDA commented
> Currently there is no uniform code style. I will format all code with the style that is most used. If @MatitoDA prefers a different one, you can comment it below so I will change it to the style you prefer.

can you explain in more detail which style you would use?

2023-07-07 19:37 UTC, Byteingpython commented
The Jetbrains default

2023-07-07 19:40 UTC, MineKing9534 commented
I would use the IntelliJ default that is applied when letting it do a code reformat. I personally also like it more to use 'var' everywhere where it is possible but we can just leave it as it is.

2023-07-07 21:55 UTC, MatitoDA requested changes

2023-07-07 21:55 UTC, MatitoDA commented on src/main/java/com/slimebot/report/assets/Status.java
> +	CLOSED("Geschlossed"),
typo

2023-07-07 21:55 UTC, MatitoDA commented on src/main/java/com/slimebot/report/assets/Type.java
> +	USER("USer");
typo

2023-07-09 11:31 UTC, Deliasama commented
Du hast das Emum verkrüppelt die funktionen sind für noch folgende projekte mit emoji

2023-07-09 12:23 UTC, MineKing9534 commented
Your requested changes were made and I resolved the merge conflicts against master. This is ready for a new review.

2023-07-09 12:30 UTC, MatitoDA commented
Whenever I run your code longer than 2 min, this error comes up

```
14:26:36 main                       Main                 INFO   Bot Version: 2.0
14:26:36 main                       Main                 INFO   test-Bot wird gestartet...
14:26:36 main                       JDA                  INFO   Login Successful!
14:26:37 JDA MainWS-ReadThread      WebSocketClient      INFO   Connected to WebSocket
14:26:37 JDA MainWS-ReadThread      JDA                  INFO   Finished Loading!
14:26:37 JDA MainWS-ReadThread      SpotifyListener      INFO   überprüfe auf neue Releases
14:28:40 JDA Gateway-Worker 1       WebSocketClient      WARN   Missed 2 heartbeats! Trying to reconnect...
java.lang.RuntimeException: java.lang.InterruptedException
	at com.slimebot.alerts.spotify.PodcastListener.<init>(PodcastListener.java:33)
	at com.slimebot.alerts.spotify.SpotifyListenerManager.register(SpotifyListenerManager.java:53)
	at com.slimebot.events.ReadyEvent.onReady(ReadyEvent.java:20)
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:442)
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:176)
	at net.dv8tion.jda.internal.requests.WebSocketClient.ready(WebSocketClient.java:212)
	at net.dv8tion.jda.internal.handle.GuildSetupController.checkReady(GuildSetupController.java:115)
	at net.dv8tion.jda.internal.handle.GuildSetupController.ready(GuildSetupController.java:102)
	at net.dv8tion.jda.internal.handle.GuildSetupNode.completeSetup(GuildSetupNode.java:377)
	at net.dv8tion.jda.internal.handle.GuildSetupNode.handleMemberChunk(GuildSetupNode.java:260)
	at net.dv8tion.jda.internal.handle.GuildSetupNode.ensureMembers(GuildSetupNode.java:394)
	at net.dv8tion.jda.internal.handle.GuildSetupNode.handleCreate(GuildSetupNode.java:220)
	at net.dv8tion.jda.internal.handle.GuildSetupController.onCreate(GuildSetupController.java:170)
	at net.dv8tion.jda.internal.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:44)
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1014)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:900)
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:878)
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1053)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1638)
	at net.dv8tion.jda.internal.JDAImpl.awaitStatus(JDAImpl.java:526)
	at net.dv8tion.jda.api.JDA.awaitStatus(JDA.java:328)
	at net.dv8tion.jda.api.JDA.awaitReady(JDA.java:378)
	at com.slimebot.alerts.spotify.PodcastListener.<init>(PodcastListener.java:30)
	... 28 more
```

2023-07-09 12:31 UTC, MineKing9534 commented
This doesn't happen for me, I will look into it in a moment.

2023-07-09 12:38 UTC, MineKing9534 commented
Okay, I found a JDA#awaitReady that shouldn't be there, does it work now?

2023-07-09 13:34 UTC, MatitoDA approved these changes

2023-07-09 13:34 UTC, merged