Config Improvements
SlimeCloud/java-SlimeBot pull request #74
Opened 2023-07-23 19:23 UTC by MineKing9534

## Checklist

 - [x] Read [Contribution Guidelines](https://github.com/SlimeCloud/java-SlimeBot#-contributing) and [Style Guides](https://github.com/SlimeCloud/java-SlimeBot#-style-guide)
 - [ ] Test the Code
 - [ ] This PR is ready to review and merge

## Description
This PR will improve the guild config handling and will also automatically create config commands and setup menus for each field

## Related Issue
#73 

## Other Information

2023-07-24 13:26 UTC, cyklon73 requested changes

2023-07-24 13:26 UTC, cyklon73 commented on src/main/java/com/slimebot/commands/config/engine/ConfigFieldType.java
> +	public final Function<ConfigField, Option> builder;
Make builder private and add a getter

2023-07-24 17:28 UTC, MatitoDA requested changes
if there are two user in a talk and one user leaves, the one who is still in talk still gets xp

2023-07-26 18:26 UTC, MatitoDA approved these changes

2023-07-26 18:26 UTC, merged